from telegram import InlineKeyboardMarkup, InlineKeyboardButton, update
from telegram.ext import Updater, CommandHandler, CallbackQueryHandler, CallbackContext, MessageHandler, Filters
import json
import fungsi as f
import menu as m
from koneksi import *


# import text as t


def start(update: update, context: CallbackContext) -> None:
    keyboard = [
        [InlineKeyboardButton("Menu", callback_data=f'1')]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    data = context.bot.getChat(chat_id=update.effective_chat.id)
    username = data.username
    id = data.id
    first_name = data.first_name
    #print(update.effective_chat.id)
    mycursor.execute("SELECT `user_id` FROM `user_db`")
    result = mycursor.fetchall()
    str = result.__str__().replace("(", "").replace(")", "").replace(",", "")
    if id.__str__() in str:
        sql = f"UPDATE user_db SET Username = %s, first_name = %s WHERE user_db.user_id = %s"
        val = (f'{username}', f'{first_name}', f'{id}')
        mycursor.execute(sql, val)
        mydb.commit()
        print(mycursor.rowcount, "record updated.")
        update.message.reply_text(f"Selamat Datang Kembali {first_name}")
    else:
        sql = "INSERT INTO user_db (Username, user_id, first_name, kode_kab) VALUES (%s,%s,%s,%s)"
        val = (f'{username}', f'{id}', f'{first_name}', f'0')
        mycursor.execute(sql, val)
        mydb.commit()
        print(mycursor.rowcount, "record inserted.")
        update.message.reply_text(f"hai {first_name}, Semoga bot ini dapat bermanfaat")

    update.message.reply_text(f'halo {first_name}, Bot ini dibuat oleh Heri sebagai tugas akhir'
                              f'\nuntuk petunjuk penggunaan klik menu dibawah ini', reply_markup=reply_markup)


def stop(update: update, context: CallbackContext) -> None:
    data = context.bot.getChat(chat_id=update.effective_chat.id)
    id = data.id
    mycursor.execute(f"DELETE FROM `user_db` WHERE `user_db`.`user_id` = {id}")
    mydb.commit()
    print('data dihapus')
    update.message.reply_text(f'anda tidak akan lagi menerima broadcast message')


def main():
    updater = Updater('2139169311:AAGsmyg_4Z9CHK7Csz6cNnH97SsWSZhC6s0')
    updater.dispatcher.add_handler(CommandHandler('start', start))
    updater.dispatcher.add_handler(CommandHandler('pasien', f.pasien))
    updater.dispatcher.add_handler(CommandHandler('rs', f.rs))
    updater.dispatcher.add_handler(CommandHandler('oksigen', f.oksigen))
    updater.dispatcher.add_handler(CommandHandler('ambulan', f.ambulan))
    updater.dispatcher.add_handler(CommandHandler('obat', f.obat))
    updater.dispatcher.add_handler(CommandHandler('stop', stop))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='vaksin'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='2'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='4'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='10'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='11'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1101'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1102'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1103'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1104'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1105'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1106'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1107'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1108'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1109'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1110'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1111'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1112'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1113'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1114'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1115'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1116'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1117'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1118'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1171'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1172'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1173'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1174'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1175'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1201'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1202'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1203'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1204'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1205'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1206'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1207'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1208'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1209'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1210'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1211'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1212'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1213'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1214'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1215'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1216'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1217'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1218'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1219'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1220'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1221'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1222'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1223'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1271'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1272'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1273'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1274'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1275'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1276'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1277'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1278'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1301'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1302'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1303'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1304'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1305'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1306'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1307'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1308'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1309'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1310'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1311'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1312'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1371'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1372'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1373'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1374'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1375'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1376'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1377'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1401'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1402'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1403'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1404'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1406'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1407'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1408'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1409'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1410'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1471'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1473'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1501'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1502'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1503'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1504'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1505'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1506'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1507'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1508'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1509'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1571'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1601'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1602'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1603'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1604'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1605'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1606'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1607'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1608'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1609'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1610'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1611'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1671'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1672'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1673'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1674'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1701'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1702'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1703'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1704'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1705'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1706'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1707'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1708'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1709'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1771'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1801'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1802'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1803'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1804'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1805'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1806'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1807'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1808'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1809'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1810'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1871'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1872'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1901'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1902'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1903'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1904'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1905'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1906'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='1971'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='2001'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='2002'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='2003'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='2004'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='2005'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='2071'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='2072'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3101'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3171'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3172'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3173'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3174'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3175'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3201'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3202'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3203'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3204'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3205'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3206'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3207'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3208'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3209'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3210'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3211'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3212'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3213'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3214'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3215'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3216'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3217'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3271'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3272'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3273'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3274'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3275'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3276'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3277'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3278'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3279'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3301'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3302'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3303'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3304'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3305'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3306'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3307'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3308'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3309'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3310'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3311'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3312'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3313'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3314'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3315'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3316'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3317'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3318'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3319'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3320'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3321'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3322'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3323'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3324'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3325'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3326'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3327'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3328'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3329'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3371'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3372'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3373'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3374'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3375'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3376'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3401'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3402'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3403'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3404'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3471'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3501'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3502'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3503'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3504'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3505'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3506'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3507'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3508'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3509'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3510'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3511'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3512'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3513'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3514'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3515'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3516'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3517'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3518'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3519'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3520'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3521'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3522'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3523'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3524'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3525'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3526'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3527'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3528'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3529'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3571'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3572'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3573'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3574'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3575'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3576'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3577'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3578'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3579'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3601'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3602'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3603'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3604'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3671'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3672'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3673'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='3674'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5101'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5102'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5103'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5104'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5105'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5106'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5107'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5108'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5130'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5171'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5201'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5202'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5203'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5204'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5205'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5206'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5207'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5208'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5271'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5272'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5301'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5302'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5303'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5304'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5305'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5306'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5307'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5308'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5309'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5310'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5311'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5312'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5313'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5314'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5316'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5320'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='5371'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6101'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6102'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6103'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6104'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6105'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6106'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6107'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6108'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6109'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6110'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6112'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6171'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6172'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6201'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6202'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6203'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6204'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6205'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6206'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6207'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6208'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6209'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6210'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6211'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6212'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6213'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6271'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6301'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6302'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6303'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6304'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6305'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6306'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6307'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6308'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6309'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6310'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6311'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6371'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6372'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6402'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6403'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6404'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6405'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6409'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6471'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6472'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6474'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6501'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6502'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6504'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='6571'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7101'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7102'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7103'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7104'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7105'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7106'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7107'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7109'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7110'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7171'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7172'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7173'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7174'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7202'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7203'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7204'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7205'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7206'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7207'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7208'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7209'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7271'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7301'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7302'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7303'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7304'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7305'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7306'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7307'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7308'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7309'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7310'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7311'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7312'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7313'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7314'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7315'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7316'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7317'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7318'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7322'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7325'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7326'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7371'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7372'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7373'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7401'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7402'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7403'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7404'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7405'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7406'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7407'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7408'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7409'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7410'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7471'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7472'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7501'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7502'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7503'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7504'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7505'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7571'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7601'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7602'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7603'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7604'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='7605'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8101'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8102'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8103'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8104'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8105'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8106'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8107'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8108'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8109'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8171'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8172'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8201'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8202'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8204'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8205'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8206'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8207'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8271'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='8272'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9101'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9102'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9103'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9104'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9105'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9106'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9107'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9108'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9171'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9201'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9202'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9203'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9204'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9205'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9208'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9210'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9211'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9212'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9213'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9214'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9215'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9216'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9217'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9220'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9227'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9228'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9230'))
    updater.dispatcher.add_handler(CallbackQueryHandler(m.answer, pattern='9271'))

    updater.dispatcher.add_handler(CallbackQueryHandler(f.obat1))

    # updater.dispatcher.add_handler(MessageHandler(Filters.text, t.text))
    updater.start_polling()
    updater.idle()


if __name__ == '__main__':
    main()
